<a href="https://colab.research.google.com/github/bigyandulal2/weatherApp/blob/main/datacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import pandas as pd
df=pd.read_csv("Data_clean.csv");

In [69]:
df.head()

,StudentID,Name,Age,City,Gender,Stream,Marks,StudyHours,Attendance,Passed
0,1,Aarav,19,KTM,female,Arts,88.0,4,80,Y
1,2,Asha,19,ktm,Femal,Science,45.0,3,90,yes
2,3,Hari,20,KTM,Female,Com,NaN,3,110,yes
3,4,Sabin,20,ktm,Male,SCIENCE,NaN,24,100,YES
4,5,Pratik,21,Pokhara,male,science,34.0,3,100,N

In [70]:
#missing values code here
df["Name"].isnull().unique() #name has no null
df["Age"].isnull().unique() #age has no null
df["City"].isnull().unique() #city has no null
df["Gender"].isnull().unique() #gender has no null
df["Stream"].isnull().unique() #stream has no null
df["Marks"].isnull().unique() #marks has null
df["Marks"].value_counts().unique()
avg_mean=df["Marks"].mean()
df["Marks"]=df["Marks"].fillna(avg_mean)

In [71]:
df["Marks"].value_counts().unique()
df["Marks"].isnull().unique()

array([False])

In [72]:
df["StudyHours"].isnull().unique() #study hours has no null

array([False])

In [73]:
df["Attendance"].isnull().unique() #Attendance has no null or nan
df["Passed"].isnull().unique() #passed has no null or nan

array([False])

In [74]:
df.isnull().sum() #the one whole code to check which column has null

StudentID     0
Name          0
Age           0
City          0
Gender        0
Stream        0
Marks         0
StudyHours    0
Attendance    0
Passed        0
dtype: int64

In [75]:
#now check duplicates for whole column
df.duplicated().sum()
#df.drop_duplicates() this checks if entire row corresponds to another row and remove
df=df.drop_duplicates(subset="StudentID") #this checks if studentId is same and remove

In [76]:
df.duplicated().sum()

np.int64(0)

In [77]:
df["Age"].unique()

array([ 19,  20,  21,  22,  -2,  18,  23, 150])

In [78]:
#case inconsistent
df["Name"].unique()
df["City"].unique()

array(['KTM', 'ktm', '  ktm  ', 'Pokhara', '  LALITPUR', 'Biratnagar',
       'KATHMANDU', 'Lalitpur', 'POKHARA', 'pokhara', 'Kathmandu'],
      dtype=object)

In [79]:
#using loc to update the city values, other values remain constant
df.loc[:,"City"]=df["City"].str.capitalize().replace({
    "Ktm":"Kathmandu",
})

In [80]:
df["Gender"].unique()

array(['female', 'Femal', 'Female', 'Male', 'male', 'F', 'M', 'FEMALE'],
      dtype=object)

In [81]:
df.loc[:,"Gender"]=df["Gender"].str.capitalize().replace({
    "F":"Female",
    "M":"Male",
    "Femal":"Female"
})

In [82]:
df["Stream"].unique()

array(['Arts', 'Science', 'Com', 'SCIENCE', 'science', 'commerce', 'Sci',
       'ARTS', 'COMMERCE', 'Commerce', 'arts'], dtype=object)

In [83]:
df.loc[:,"Stream"]=df["Stream"].str.capitalize().replace({
    "Com":"Commerce",
    "Sci":"Science",
})

In [84]:
df["Stream"].unique()

array(['Arts', 'Science', 'Commerce'], dtype=object)

In [85]:
df["Passed"].unique()

array(['Y', 'yes', 'YES', 'N', 'Yes', 'no', 'No'], dtype=object)

In [86]:
df.loc[:,"Passed"]=df["Passed"].str.capitalize().replace({
    "Y":"Yes",
    "N":"No"
})

In [87]:
df["Passed"].unique()

array(['Yes', 'No'], dtype=object)

In [88]:
#impossible values for example marks and studyHours
df[(df["StudyHours"]<0) | (df["StudyHours"]> 24)]

,StudentID,Name,Age,City,Gender,Stream,Marks,StudyHours,Attendance,Passed
11,12,Asha,19,Kathmandu,Female,Arts,82.000000,25,110,Yes
16,17,Sita,23,Kathmandu,Female,Commerce,78.000000,25,75,Yes
18,19,Anil,20,Biratnagar,Male,Science,55.000000,25,75,Yes
20,21,Sita,19,Biratnagar,Male,Science,82.000000,25,85,Yes
25,26,Gita,150,Kathmandu,Male,Science,78.000000,25,90,No
31,32,Aarav,-2,Kathmandu,Female,Arts,73.943182,25,95,No
39,40,Hari,19,Kathmandu,Female,Arts,78.000000,25,95,No
58,59,Asha,20,lalitpur,Female,Commerce,105.000000,25,90,No
82,83,Sujal,150,Kathmandu,Female,Arts,82.000000,25,85,No
85,86,Ramesh,150,Lalitpur,Female,Arts,45.000000,25,100,Yes
90,91,Anil,23,Pokhara,Female,Arts,73.943182,25,95,Yes

In [89]:
df=df[(df["StudyHours"] > 0) & (df["StudyHours"] <24)] #i want both of the condition to be true so, updating the dataframe accordingly

In [90]:
df[(df["StudyHours"]<0) | (df["StudyHours"]> 24)] #after updating no any data here now oops

Empty DataFrame
Columns: [StudentID, Name, Age, City, Gender, Stream, Marks, StudyHours, Attendance, Passed]
Index: []

In [91]:
df=df[(df["Marks"] <= 100)] #only accepts marks equal or less than 100

In [92]:
df[df["Marks"]> 100] # now all removed marks

Empty DataFrame
Columns: [StudentID, Name, Age, City, Gender, Stream, Marks, StudyHours, Attendance, Passed]
Index: []

In [93]:
# use of loc and iloc
df.loc[0,"Marks"]

np.float64(88.0)

In [94]:
df.columns

Index(['StudentID', 'Name', 'Age', 'City', 'Gender', 'Stream', 'Marks',
       'StudyHours', 'Attendance', 'Passed'],
      dtype='object')

In [95]:
df.index

Index([ 0,  1,  2,  4,  6,  7,  8, 10, 12, 13, 15, 17, 19, 21, 23, 24, 27, 28,
       29, 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 54, 57, 60, 61, 62, 64, 65, 67, 68, 69, 71, 72, 73, 75, 76,
       77, 78, 79, 80, 81, 83, 84, 86, 88, 89, 91, 92, 93, 94, 96, 97, 99],
      dtype='int64')

In [96]:
df.iloc[45]

StudentID            66
Name              Nisha
Age                 150
City          Kathmandu
Gender           Female
Stream         Commerce
Marks              92.0
StudyHours            5
Attendance           95
Passed               No
Name: 65, dtype: object

In [97]:
df.loc[1:12,["Marks","Name"]]

        Marks     Name
1   45.000000     Asha
2   73.943182     Hari
4   34.000000   Pratik
6   88.000000    Nisha
7   34.000000  Prakash
8   82.000000     Riya
10  88.000000   Sunita
12  73.943182   Alisha